"""new table

Revision ID: 16cc029088ab
Revises: 52d3c77b83fc
Create Date: 2022-12-01 12:15:31.925924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16cc029088ab'
down_revision = '52d3c77b83fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_login_data',
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('email_id', sa.String(), nullable=True),
    sa.Column('mobile_no', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('retype_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_name'),
    sa.UniqueConstraint('user_name', 'email_id', 'mobile_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_login_data')
    # ### end Alembic commands ###
